### ISSUE TITLE
TODO: Implement Frontend and Backend Systems

### ISSUE THREAD

**Issue by YaruG1022** [YaruG1022/WSU-SU21-CPTS322-Project#3]
As a Product Developer,
I want to develop a comprehensive management platform,
So that users can efficiently interact with a robust frontend interface and a secure backend system.
### Frontend: 
- [x] A HTML platform UI.
  - [x] Webpages: homepage, inventory, donation, transaction, report generating.
  - [x] Other displays that enhance visual design.
  - [x] Account Interface: log-in, sign-up, etc..
  - [x] Additional features that improve usability, convenience, and safety.
### Backend: 
- [x] SQL database: storing inventory and donation info, account data, and transactions.
- [x] Interactive functionalities (Flask).

### Story Points: 11; - Require a month to be completed.
